apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: webserver
  labels:
    name: flask-mysql-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: webserver
    name: pvc-mysql
  gcePersistentDisk:
    pdName: mysql-disk
